# Generated by Django 3.0.5 on 2020-05-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200505_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlogger',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
