# Generated by Django 3.0.5 on 2020-05-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200505_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlogger',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
