# Generated by Django 3.0.5 on 2020-05-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_habitlogger_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlogger',
            name='current_total_habits',
            field=models.IntegerField(default=1),
        ),
    ]
